
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {createGame,act,aiAction,makeDeck,validate} from '../src/engine.js';
import {MAPS,STRATEGIES} from '../src/data.js';
export async function browserChecks(browser,url='http://127.0.0.1:4173/'){
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],checks=[];
 page.on('pageerror',e=>errors.push(e.message));
 const click=a=>page.locator('[data-action="'+a+'"]').click();
 const state=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));
 async function load(s){
  await page.goto(url);await page.evaluate(s=>localStorage.setItem('shadowline-war-v1',JSON.stringify(s)),s);await page.reload();await click('load');
  if(s.opt.mode==='local')await click('ready');
 }
 async function drain(){for(let n=0;n<20&&await page.locator('.event-screen').count();n++)await click('next-event')}
 let s=createGame({strategies:false,mode:'ai',timer:30,eventSeconds:3,seed:119});s.active=1;s.raid=true;
 await load(s);await page.locator('.event-invasion').waitFor();
 assert.match(await page.locator('.event-map-node.hit').innerText(),/西境指挥部/);
 const invaded=await state();assert.equal(invaded.phase,'attack');assert.equal(invaded.battle.lines[0].length,3);
 await page.getByRole('button',{name:'暂停',exact:true}).click();await page.waitForTimeout(3200);
 assert.equal(await page.locator('.event-invasion').count(),1);assert.deepEqual(await state(),invaded);
 await click('close');await page.waitForTimeout(400);assert.equal(await page.locator('.event-invasion').count(),1);
 await page.locator('.event-garrison').waitFor({timeout:4000});await drain();
 assert.equal(await page.locator('.hand-tray .playing-card').count(),9);
 await page.waitForFunction(()=>/30|29/.test(document.querySelector('#clock')?.textContent));
 checks.push('AI invasion target, automatic 3-second queue, pause, preserved action timer, visible map garrisons, scale-stable nodes and rank/suit hand sorting');
 s=createGame({strategies:false,mode:'ai'});s.players[0].strategies=['conscription'];await load(s);await page.locator('[data-action="use-strategy"][data-id="conscription"]').click();
 await click('next-event');assert.equal(await page.locator('.event-cards .playing-card:not(.back)').count(),2);
 assert.equal(await page.locator('.event-cards + .event-progress').count(),1);
 assert.equal(await page.locator('.event-cards .new-card-badge').count(),2);await drain();
 assert.equal(await page.locator('.hand-tray .new-card-badge').count(),2);checks.push('strengthened conscription draws two cards with face animations and persistent hand markers');
 s=createGame({strategies:false,mode:'ai'});s.players[0].strategies=['isr'];await load(s);await page.locator('[data-action="use-strategy"][data-id="isr"]').click();
 assert.equal(await page.locator('.targeting-note').count(),1);
 const enemy=s.fields.find(f=>f.owner===1);await page.locator('[data-action="focus"][data-id="'+enemy.id+'"]').click();
 await page.setViewportSize({width:390,height:600});const strategyEventLayout=await page.evaluate(()=>{const screen=document.querySelector('.event-screen'),panel=document.querySelector('.event-panel'),sr=screen.getBoundingClientRect(),pr=panel.getBoundingClientRect();return {screenDisplay:getComputedStyle(screen).display,screen:{left:sr.left,right:sr.right,top:sr.top,bottom:sr.bottom},panel:{left:pr.left,right:pr.right,top:pr.top,bottom:pr.bottom,width:pr.width},viewport:{width:innerWidth,height:innerHeight},page:{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight}}});assert.equal(strategyEventLayout.screenDisplay,'flex');assert.ok(strategyEventLayout.panel.width>=350&&strategyEventLayout.panel.left>=0&&strategyEventLayout.panel.right<=strategyEventLayout.viewport.width&&strategyEventLayout.panel.top>=0&&strategyEventLayout.panel.bottom<=strategyEventLayout.viewport.height&&strategyEventLayout.page.width<=strategyEventLayout.viewport.width,JSON.stringify(strategyEventLayout));await page.setViewportSize({width:1440,height:1000});await drain();
 assert.ok((await state()).fields.find(f=>f.id===enemy.id).garrison.some(c=>c.open));
 await page.locator('[data-action="reserve"][data-player="0"]').click();assert.equal(await page.locator('.garrison-roster .playing-card:not(.back)').count(),3);await click('close');
 checks.push('strategy target selection, stable mobile strategy event panel and garrison roster');
 s=createGame({strategies:false,mode:'local',eventSeconds:3});await load(s);
 const center=s.fields.find(f=>f.id==='center_town');const stationed=s.players[0].hand[0].id;
 await page.locator('[data-action="focus"][data-id="'+center.id+'"]').click();await page.locator('[data-action="card"][data-id="'+stationed+'"]').click();await click('occupy');
 assert.equal(await page.locator('.event-occupation').count(),1);assert.equal(await page.locator('.hand-tray').count(),0);
 await drain();assert.equal(await page.locator('[data-action="ready"]').count(),0);assert.equal(await page.locator('.hand-tray').count(),1);assert.equal((await state()).actionSpent,true);assert.match(await page.locator('.action-reminder').innerText(),/主要行动已完成/);await click('supply');await drain();assert.equal((await state()).active,0);assert.equal((await state()).supplyUsed,true);await click('pass');await drain();assert.equal(await page.locator('[data-action="ready"]').count(),1);assert.equal(await page.locator('.hand-tray').count(),0);
 await click('ready');await page.locator('[data-action="reserve"][data-player="0"]').click();
 assert.equal(await page.locator('.garrison-roster .playing-card:not(.back)').count(),1);
 assert.equal(await page.locator('.garrison-roster .playing-card.back').count(),3);
 checks.push('occupation keeps the active player for remaining logistics, explicit end turn triggers hotseat handoff, and privacy is preserved');
 // Reach an actual attacker deployment with a usable blitzkrieg.
 s=createGame({rules:'classic',strategies:false,mode:'local',seed:119});
 s=act(s,s.active,{type:'deploy',cards:[{id:s.players[s.active].hand.sort((a,b)=>a.rank-b.rank)[0].id,open:true}]}).state;
 s.players[s.active].strategies=['blitzkrieg'];
 const deployment=aiAction(s,s.active);assert.equal(deployment.type,'deploy');
 await load(s);for(const c of deployment.cards){await page.locator('[data-action="card"][data-id="'+c.id+'"]').click();if(!c.open)await page.locator('[data-action="card"][data-id="'+c.id+'"]').click()}
 await click('deploy');await drain();assert.equal((await state()).phase,'tactics');
 await page.locator('[data-action="use-strategy"][data-id="blitzkrieg"]').click();assert.equal(await page.locator('.event-strategy').count(),1);await drain();
 assert.equal((await state()).players[1].wins,1);checks.push('actual deployment to tactical window and successful blitzkrieg');
 await page.setViewportSize({width:375,height:812});s=createGame({strategies:false,mode:'ai',eventSeconds:5});s.active=1;s.raid=true;await load(s);await page.locator('.event-invasion').waitFor();
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:fileURLToPath(new URL('../../shadowline-event-mobile.png',import.meta.url)),fullPage:true});
 await page.getByRole('button',{name:'暂停',exact:true}).click();await click('close');await drain();
 const mobileMetrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,width:innerWidth,height:innerHeight,battle:document.querySelector('.battle-area')?.getBoundingClientRect().toJSON(),hand:document.querySelector('.hand-tray')?.getBoundingClientRect().toJSON(),intel:document.querySelector('.intel-panel')?.getBoundingClientRect().toJSON()}));
 assert.ok(mobileMetrics.scrollWidth<=mobileMetrics.width&&mobileMetrics.scrollHeight<=mobileMetrics.height&&mobileMetrics.hand?.height>=104&&mobileMetrics.hand.bottom<=mobileMetrics.height&&mobileMetrics.intel?.height>=56&&mobileMetrics.intel.bottom<=mobileMetrics.height,JSON.stringify(mobileMetrics));
 await page.setViewportSize({width:834,height:1112});
 const tabletMetrics=await page.evaluate(()=>({scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight,width:innerWidth,height:innerHeight,hand:document.querySelector('.hand-tray')?.getBoundingClientRect().toJSON(),intel:document.querySelector('.intel-panel')?.getBoundingClientRect().toJSON()}));
 assert.ok(tabletMetrics.scrollWidth<=tabletMetrics.width&&tabletMetrics.scrollHeight<=tabletMetrics.height&&tabletMetrics.hand?.height>=122&&tabletMetrics.hand.bottom<=tabletMetrics.height&&tabletMetrics.intel?.height>=64&&tabletMetrics.intel.bottom<=tabletMetrics.height,JSON.stringify(tabletMetrics));checks.push('iPhone and iPad battle layouts reserve visible hand and command trays without page overflow');
 // Every campaign map must open at a useful fitted scale with separated, fully visible nodes.
 for(const map of MAPS){s=createGame({strategies:false,mode:'ai',map:map.id,seed:1400+map.fields.length});await load(s);await page.waitForTimeout(120);if(map===MAPS[0]){const rankOrder=await page.locator('.hand-tray [data-action="card"]').evaluateAll(xs=>xs.map(x=>Number(x.dataset.id))),rankExpected=(await state()).players[0].hand.slice().sort((a,b)=>a.rank-b.rank||a.suit-b.suit||a.id-b.id).map(c=>c.id);assert.deepEqual(rankOrder,rankExpected);await page.locator('[data-action="hand-sort"][data-id="suit"]').click();const suitOrder=await page.locator('.hand-tray [data-action="card"]').evaluateAll(xs=>xs.map(x=>Number(x.dataset.id))),suitExpected=(await state()).players[0].hand.slice().sort((a,b)=>a.suit-b.suit||a.rank-b.rank||a.id-b.id).map(c=>c.id);assert.deepEqual(suitOrder,suitExpected);const tones=await page.evaluate(()=>{const a=getComputedStyle(document.querySelector('.map-node.owner-0')),b=getComputedStyle(document.querySelector('.map-node.owner-1'));return {a:a.borderLeftColor,b:b.borderLeftColor,abg:a.backgroundImage,bbg:b.backgroundImage}});assert.notEqual(tones.a,tones.b);assert.notEqual(tones.abg,tones.bbg)}const layout=await page.evaluate(()=>{const saved=JSON.parse(localStorage.getItem('shadowline-war-v1')),stage=document.querySelector('.map-stage').getBoundingClientRect(),nodes=[...document.querySelectorAll('.map-node')].map(e=>{const r=e.getBoundingClientRect();return {l:r.left,r:r.right,t:r.top,b:r.bottom,w:r.width,h:r.height}}),overlap=(a,b)=>Math.max(0,Math.min(a.r,b.r)-Math.max(a.l,b.l))*Math.max(0,Math.min(a.b,b.b)-Math.max(a.t,b.t));return {scale:Number(getComputedStyle(document.querySelector('.map-camera')).getPropertyValue('--map-scale')),inside:nodes.every(n=>n.l>=stage.left-1&&n.r<=stage.right+1&&n.t>=stage.top-1&&n.b<=stage.bottom+1),overlaps:nodes.flatMap((a,i)=>nodes.slice(i+1).map(b=>overlap(a,b))).filter(n=>n>1).length,spanX:Math.max(...nodes.map(n=>n.r))-Math.min(...nodes.map(n=>n.l)),stageWidth:stage.width,miniCards:document.querySelectorAll('.map-mini-card').length,totalGarrison:saved.fields.reduce((n,f)=>n+f.garrison.length,0),nodeLayerOutsideCamera:document.querySelectorAll('.map-stage > .node-layer').length===1&&!document.querySelector('.map-camera .node-layer')}});assert.ok(layout.scale>=1&&layout.inside&&layout.overlaps===0&&layout.spanX>=Math.min(420,layout.stageWidth*.42)&&layout.miniCards===layout.totalGarrison&&layout.nodeLayerOutsideCamera,map.id+' '+JSON.stringify(layout));const nodeBefore=await page.locator('.map-node').first().evaluate(el=>el.getBoundingClientRect().width);await page.getByRole('button',{name:'放大战场'}).click();const nodeAfter=await page.locator('.map-node').first().evaluate(el=>el.getBoundingClientRect().width);assert.ok(Math.abs(nodeBefore-nodeAfter)<1,map.id+' '+JSON.stringify({nodeBefore,nodeAfter}));await page.getByRole('button',{name:'重置战场视图'}).click()}
 checks.push('all eight maps auto-fit to the battlefield with no overlapping or clipped location controls');
 const routeOrigin=s.fields.find(f=>f.links.length),edgeCount=s.fields.reduce((n,f)=>n+f.links.length,0)/2;
 assert.equal(await page.locator('.topology-lines .route-base').count(),edgeCount);assert.ok(Number(await page.locator('.topology-lines .route-base').first().evaluate(e=>getComputedStyle(e).opacity))>=.5);
 await page.locator('[data-action="focus"][data-id="'+routeOrigin.id+'"]').click();
 const routeFeedback=await page.evaluate(()=>({active:document.querySelectorAll('.map-route.active').length,pulses:document.querySelectorAll('.route-pulse').length,neighbors:document.querySelectorAll('.map-node.route-neighbor').length,routeAnimation:getComputedStyle(document.querySelector('.route-pulse')).animationName,nodeAnimation:getComputedStyle(document.querySelector('.map-node.route-neighbor'),'::before').animationName}));
 assert.deepEqual(routeFeedback,{active:routeOrigin.links.length,pulses:routeOrigin.links.length,neighbors:routeOrigin.links.length,routeAnimation:'route-flow',nodeAnimation:'route-node-pulse'});checks.push('persistent route network and animated selected-location pulses highlight exactly the directly connected locations');
 // Stress the campaign HUD with twelve cards, three selected cards, target actions and a tactic.
 s=createGame({strategies:false,mode:'ai',map:'china_civil_war',seed:913});s.players[0].hand.push(...s.deck.splice(0,3));s.players[0].strategies=['spy'];
 await load(s);assert.equal(await page.locator('.geo-backdrop').count(),1);assert.equal(await page.locator('.map-camera .topology-lines').count(),0);assert.equal(await page.locator('.map-stage > .topology-lines').count(),1);assert.ok(await page.locator('.geo-backdrop .land').count()>0);
 await page.locator('[data-action="supply-ledger"][data-player="0"]').click();assert.match(await page.locator('.supply-ledger').innerText(),/据点产出|本回合净变化/);await click('close');
 const adjacent=s.fields.find(f=>f.owner===null&&f.links.some(id=>s.fields.find(x=>x.id===id)?.owner===0));
 await page.locator('[data-action="focus"][data-id="'+adjacent.id+'"]').click();const stressCards=page.locator('.hand-tray [data-action="card"]');for(let i=0;i<3;i++)await stressCards.nth(i).click();
 for(const viewport of [{width:390,height:600},{width:390,height:659},{width:390,height:844},{width:430,height:700},{width:834,height:1112}]){
  await page.setViewportSize(viewport);
  await page.waitForTimeout(250);
  const layout=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}},one=s=>document.querySelector(s),all=s=>[...document.querySelectorAll(s)],inside=(r,p)=>r.left>=p.left-1&&r.right<=p.right+1&&r.top>=p.top-1&&r.bottom<=p.bottom+1,overlap=(a,b)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));const top=all('.topbar>*').filter(e=>getComputedStyle(e).display!=='none').map(rect),pairOverlap=top.flatMap((a,i)=>top.slice(i+1).map(b=>overlap(a,b))).reduce((a,b)=>a+b,0),target=rect(one('.target-bar')),hand=rect(one('.hand-tray')),intel=rect(one('.intel-panel')),map=rect(one('.map-stage')),cards=all('.hand-card-shell>.playing-card').map(rect),nodes=all('.map-node').map(rect),intelChildren=all('.intel-panel > *').filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height}).map(rect),maxNodeOverlap=nodes.flatMap((a,i)=>nodes.slice(i+1).map(b=>overlap(a,b)/Math.min(a.width*a.height,b.width*b.height))).reduce((a,b)=>Math.max(a,b),0);return {viewport:{width:innerWidth,height:innerHeight,scrollWidth:document.documentElement.scrollWidth,scrollHeight:document.documentElement.scrollHeight},topbar:rect(one('.topbar')),armies:rect(one('.armies')),pairOverlap,maxNodeOverlap,target,hand,intel,map,cards,actionsInside:all('.target-actions button').map(rect).every(r=>inside(r,target)),cardsInside:cards.every(r=>inside(r,hand)),cardOrder:cards.every((r,i)=>!i||r.left>cards[i-1].left)&&cards.every((r,i)=>i===cards.length-1||cards[i+1].left-r.left>=18),intelInside:intelChildren.every(r=>inside(r,intel)),intelUsesWidth:rect(one('.tactic-dock')).right>=intel.right-12,controlsInside:all('.map-controls button').map(rect).every(r=>inside(r,map))}});
  assert.ok(layout.viewport.scrollWidth<=layout.viewport.width&&layout.viewport.scrollHeight<=layout.viewport.height&&layout.pairOverlap===0&&layout.maxNodeOverlap<.3&&layout.actionsInside&&layout.cardsInside&&layout.cardOrder&&layout.intelInside&&layout.intelUsesWidth&&layout.controlsInside,JSON.stringify({viewport,layout}));
 if(viewport.width<=520)assert.ok(layout.topbar.height<=48&&layout.armies.height<=58&&layout.hand.height<=104,JSON.stringify({viewport,layout}));
 }
 checks.push('short Chrome viewport matrix keeps top HUD, target actions, twelve-card hand, map controls and full-width tactic dock separated and visible; logistics ledger opens from supply and historical map has a geographic backdrop');
 // Five-card capital defense must stay separated from headings and actions on iPhone Chrome.
 s=createGame({strategies:false,mode:'ai',map:'western_front',seed:1414});const paris=s.fields.find(f=>f.id==='paris');while(paris.garrison.length<5)paris.garrison.push({...s.players[1].hand.pop(),open:paris.garrison.length<3});s.raid=true;s=act(s,0,{type:'attack',field:paris.id}).state;validate(s);await load(s);
 for(const viewport of [{width:390,height:600},{width:390,height:844}]){await page.setViewportSize(viewport);await page.waitForTimeout(200);const layout=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {left:r.left,right:r.right,top:r.top,bottom:r.bottom,width:r.width,height:r.height}},inside=(r,p)=>r.left>=p.left-1&&r.right<=p.right+1&&r.top>=p.top-1&&r.bottom<=p.bottom+1,area=(a,b)=>Math.max(0,Math.min(a.right,b.right)-Math.max(a.left,b.left))*Math.max(0,Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top));const battle=rect(document.querySelector('.battle-area')),rows=[...document.querySelector('.battle-area').children].map(rect),lines=[...document.querySelectorAll('.battle-line')];return {viewport:{w:innerWidth,h:innerHeight,sw:document.documentElement.scrollWidth,sh:document.documentElement.scrollHeight},battle,rowsSeparated:rows.every((r,i)=>!i||area(rows[i-1],r)<=Math.min(r.width,rows[i-1].width)*4),cardsInside:lines.every(line=>[...line.querySelectorAll('.playing-card,.card-slot')].every(c=>inside(rect(c),rect(line)))),slots:[...document.querySelectorAll('.enemy-line .playing-card,.enemy-line .card-slot')].length,hand:rect(document.querySelector('.hand-tray')),intel:rect(document.querySelector('.intel-panel'))}});assert.ok(layout.viewport.sw<=layout.viewport.w&&layout.viewport.sh<=layout.viewport.h&&layout.rowsSeparated&&layout.cardsInside&&layout.slots===5&&layout.hand.bottom<=layout.viewport.h&&layout.intel.bottom<=layout.viewport.h,JSON.stringify({viewport,layout}))}
 checks.push('390px iPhone battle grid keeps a five-card capital line, labels, comparison text and action controls in separate rows');
 await page.goto(url);await page.evaluate(()=>localStorage.removeItem('shadowline-war-v1'));await page.reload();await page.setViewportSize({width:390,height:844});await page.locator('[data-action="map"][data-id="korea"]').click();await page.locator('details.advanced summary').click();assert.equal(await page.locator('[data-option="deployment"] option').count(),2);assert.equal(await page.locator('[data-option="deployment"]').inputValue(),'historical');assert.match(await page.locator('[data-option="deployment"] option').last().textContent(),/1950年6月/);await page.locator('[data-option="deployment"]').selectOption('standard');assert.equal(await page.locator('[data-option="deployment"]').inputValue(),'standard');
 assert.equal(await page.locator('.top-actions [data-action="tutorial"]').count(),1);await page.locator('[data-action="tutorial"]').click();assert.equal(await page.locator('.tutorial-progress i').count(),8);
 for(let step=0;step<8;step++){await page.locator('.tutorial-shot img').waitFor();await page.waitForFunction(()=>{const img=document.querySelector('.tutorial-shot img');return img?.complete&&img.naturalWidth>500});assert.match(await page.locator('.tutorial-head>span').innerText(),new RegExp('^'+(step+1)+' / 8$'));const box=await page.locator('.modal').evaluate(e=>{const r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height,viewport:innerHeight,scrollHeight:e.scrollHeight}});assert.ok(box.top>=0&&box.bottom<=box.viewport&&box.height<=box.viewport,JSON.stringify(box));await page.locator('[data-action="tutorial-step"]').last().click()}
 assert.equal(await page.locator('.modal-overlay').count(),0);checks.push('eight-step illustrated tutorial loads every real UI screenshot, advances correctly and fits a 390px iPhone viewport');
 assert.deepEqual(errors,[]);await page.close();return {checks,pageErrors:errors};
}

export async function counterplayCheck(browser,url='http://127.0.0.1:4173/'){
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];
 page.on('pageerror',e=>errors.push(e.message));
 let s=createGame({rules:'classic',strategies:false,mode:'ai',first:1,eventSeconds:3});
 const deck=makeDeck(),take=spec=>spec.map(([rank,suit])=>deck.find(c=>c.rank===rank&&c.suit===suit));
 s.players[0].hand=take([[4,0],[9,1]]);s.players[1].hand=take([[1,2],[6,3]]);
 const used=new Set(s.players.flatMap(p=>p.hand.map(c=>c.id)));s.deck=deck.filter(c=>!used.has(c.id));validate(s);
 for(const p of [1,0])s=act(s,p,{type:'deploy',cards:s.players[p].hand.map((c,i)=>({id:c.id,open:i===0}))}).state;
 const humanHidden=s.battle.lines[0][1].id,skirmish=s.skirmish;
 await page.goto(url);await page.evaluate(s=>localStorage.setItem('shadowline-war-v1',JSON.stringify(s)),s);await page.reload();await page.locator('[data-action="load"]').click();
 await page.locator('.event-reveal').waitFor();
 let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));
 assert.equal(saved.active,0);assert.equal(saved.skirmish,skirmish);assert.equal(saved.players.map(p=>p.wins).join(','),'0,0');
 await page.locator('[data-action="next-event"]').click();
 const hidden=page.locator('[data-action="reveal-card"][data-id="'+humanHidden+'"]');assert.equal(await hidden.count(),1);
 assert.match(await hidden.innerText(),/点击翻开/);assert.match(await page.locator('.battle-actions').innerText(),/当前比较只计算明牌/);
 await hidden.click();assert.match(await page.locator('.battle-actions').innerText(),/选择后牌型/);assert.equal(await page.locator('[data-action="reveal"]').isEnabled(),true);await page.locator('[data-action="reveal"]').click();
 saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));assert.equal(saved.players[0].wins,1);
 assert.deepEqual(errors,[]);await page.close();
 return 'AI counterlead preserves human hidden-card button; human reveals and wins the same skirmish';
}

export async function strategyMarketCheck(browser,url='http://127.0.0.1:4173/'){
 const page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const loadState=async state=>{await page.goto(url);await page.evaluate(s=>localStorage.setItem('shadowline-war-v1',JSON.stringify(s)),state);await page.reload();await page.locator('[data-action="load"]').click()};
 const strategyIds=STRATEGIES.map(card=>card.id);
 for(const viewport of [{width:390,height:600},{width:834,height:1112},{width:1440,height:900}]){
  await page.setViewportSize(viewport);
  for(let offset=0;offset<strategyIds.length;offset+=3){
   const group=strategyIds.slice(offset,offset+3),layoutState=createGame({strategies:false,mode:'ai',seed:2500+offset});layoutState.opt.strategies=true;layoutState.players[0].strategies=group;layoutState.strategyLocked=[[],[]];
   await loadState(layoutState);
   const tokens=page.locator('.tactic-dock>.strategy-token');assert.equal(await tokens.count(),group.length);
   for(const id of group){await page.locator('[data-action="use-strategy"][data-id="'+id+'"]').hover();await page.waitForTimeout(180);const tipLayout=await page.evaluate(()=>{const tips=[...document.querySelectorAll('.strategy-tooltip')].filter(e=>Number(getComputedStyle(e).opacity)>.5),r=tips[0]?.getBoundingClientRect();return {count:tips.length,inside:!!r&&r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight}});assert.deepEqual(tipLayout,{count:1,inside:true},id+' '+JSON.stringify({viewport,tipLayout}))}
   layoutState.players[0].strategies=[];layoutState.players[0].supply=30;layoutState.strategyMarket=group;layoutState.strategyDeck=strategyIds.filter(id=>!group.includes(id));layoutState.marketBought=false;
   await loadState(layoutState);await page.locator('[data-action="open-market"]').click();const marketLayout=await page.evaluate(()=>{const rect=e=>{const r=e.getBoundingClientRect();return {l:r.left,r:r.right,t:r.top,b:r.bottom}},overlap=(a,b)=>Math.max(0,Math.min(a.r,b.r)-Math.max(a.l,b.l))*Math.max(0,Math.min(a.b,b.b)-Math.max(a.t,b.t)),cards=[...document.querySelectorAll('.market-list>.market-card')].map(rect),modal=document.querySelector('.modal').getBoundingClientRect();return {count:cards.length,overlaps:cards.flatMap((a,i)=>cards.slice(i+1).map(b=>overlap(a,b))).filter(n=>n>1).length,inside:modal.left>=0&&modal.right<=innerWidth&&modal.top>=0&&modal.bottom<=innerHeight,pageWidth:document.documentElement.scrollWidth,viewportWidth:innerWidth}});assert.equal(marketLayout.count,3);assert.ok(!marketLayout.overlaps&&marketLayout.inside&&marketLayout.pageWidth<=marketLayout.viewportWidth,group.join(',')+' '+JSON.stringify({viewport,marketLayout}))
  }
 }
 await page.setViewportSize({width:1440,height:900});
 let s=createGame({strategies:false,mode:'local',eventSeconds:1});s.opt.strategies=true;s.players[0].supply=7;s.strategyMarket=['conscription','spy','blitzkrieg'];s.strategyDeck=['rank_up'];s.strategyDiscard=[];s.strategyLocked=[[],[]];s.marketBought=false;const rotatingCapital=s.fields.find(f=>f.owner===0);rotatingCapital.garrison[0].open=true;const revealedId=rotatingCapital.garrison[0].id;
 await page.goto(url);await page.evaluate(s=>localStorage.setItem('shadowline-war-v1',JSON.stringify(s)),s);await page.reload();await page.locator('[data-action="load"]').click();await page.locator('[data-action="ready"]').click();
 await page.setViewportSize({width:977,height:792});const neutral=s.fields.find(f=>f.owner===null);await page.locator('[data-action="focus"][data-id="'+neutral.id+'"]').click();const guidedOccupy=page.locator('[data-action="occupy"]');assert.equal(await guidedOccupy.isEnabled(),true);assert.match(await guidedOccupy.getAttribute('title'),/请先从下方手牌选择驻军/);await guidedOccupy.click();assert.match(await page.locator('#toast').innerText(),/必须选择/);await page.locator('[data-action="card"]').first().click();
 const targetBounds=await page.evaluate(()=>{const bar=document.querySelector('.target-bar').getBoundingClientRect(),button=document.querySelector('[data-action="occupy"]').getBoundingClientRect();return {bar:{top:bar.top,bottom:bar.bottom},button:{top:button.top,bottom:button.bottom},visible:button.width>0&&button.height>0}});assert.ok(targetBounds.visible&&targetBounds.button.top>=targetBounds.bar.top&&targetBounds.button.bottom<=targetBounds.bar.bottom,JSON.stringify(targetBounds));
 const capital=s.fields.find(f=>f.owner===0);await page.locator('[data-action="focus"][data-id="'+capital.id+'"]').click();const ownActionBounds=await page.evaluate(()=>{const bar=document.querySelector('.target-bar').getBoundingClientRect(),buttons=[...document.querySelectorAll('.target-actions button')].map(e=>{const r=e.getBoundingClientRect();return {label:e.textContent.trim(),top:r.top,bottom:r.bottom,width:r.width,height:r.height}});return {bar:{top:bar.top,bottom:bar.bottom},buttons}});assert.ok(ownActionBounds.buttons.length===5&&ownActionBounds.buttons.every(b=>b.width>0&&b.height>0&&b.top>=ownActionBounds.bar.top&&b.bottom<=ownActionBounds.bar.bottom),JSON.stringify(ownActionBounds));assert.ok(ownActionBounds.buttons.some(b=>b.label==='补充暗牌 · 2 补给'));
 await page.locator('[data-action="open-rotation"]').click();assert.match(await page.locator('.modal').innerText(),/撤下的明牌进入公开牌堆/);await page.locator('[data-action="rotate-out"][data-id="'+revealedId+'"]').click();await page.locator('[data-action="rotate-in"]').first().click();assert.equal(await page.locator('[data-action="rotate-submit"]').isEnabled(),true);await page.locator('[data-action="rotate-submit"]').click();assert.match(await page.locator('.event-garrison').innerText(),/1 张明牌进入公开牌堆/);await page.locator('[data-action="next-event"]').click();let rotated=await page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));assert.equal(rotated.players[0].supply,6);assert.ok(rotated.players[0].reserve.some(c=>c.id===revealedId));assert.equal(rotated.rapidRedeployUsed,true);
 assert.equal(await page.locator('.strategy-shop-trigger').count(),0);assert.equal(await page.locator('.strategy-shop-button').count(),1);assert.equal(await page.locator('.market-card').count(),0);assert.equal(await page.evaluate(()=>[document.documentElement.scrollWidth<=innerWidth,document.documentElement.scrollHeight<=innerHeight].join(',')),'true,true');
 await page.locator('[data-action="open-market"]').click();assert.equal(await page.locator('.market-card').count(),3);assert.match(await page.locator('[data-action="buy-strategy"][data-id="conscription"]').innerText(),/购买 · 3 补给/);assert.match(await page.locator('[data-action="buy-strategy"][data-id="blitzkrieg"]').innerText(),/补给不足 · 需 7/);await page.locator('[data-action="buy-strategy"][data-id="conscription"]').click();
 assert.equal(await page.locator('.event-purchase').count(),1);assert.match(await page.locator('.event-strategy-card').innerText(),/征召令/);
 let saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));assert.equal(saved.players[0].supply,3);assert.ok(saved.strategyLocked[0].includes('conscription'));assert.equal(saved.strategyMarket.length,3);
 await page.locator('[data-action="next-event"]').click();await page.locator('[data-action="open-market"]').click();assert.equal(await page.locator('.market-buy').allTextContents().then(xs=>xs.every(x=>/本回合已购/.test(x))),true);await page.locator('[data-action="close"]').click();assert.match(await page.locator('.strategy-tooltip').textContent(),/下一个地图回合/);await page.locator('.strategy-token').hover();await page.waitForTimeout(220);assert.equal(await page.locator('.strategy-tooltip').isVisible(),true);
 await page.locator('[data-action="pass"]').click();while(await page.locator('.event-screen').count())await page.locator('[data-action="next-event"]').click();await page.locator('[data-action="ready"]').click();await page.locator('[data-action="pass"]').click();while(await page.locator('.event-screen').count())await page.locator('[data-action="next-event"]').click();await page.locator('[data-action="ready"]').click();
 saved=await page.evaluate(()=>JSON.parse(localStorage.getItem('shadowline-war-v1')));assert.equal(saved.strategyLocked[0].length,0);assert.equal(saved.active,0);assert.deepEqual(errors,[]);await page.close();return 'all strategy cards fit their phone, tablet and desktop docks, tooltips and market rows; rotation and market state transitions remain valid';
}
